### ISSUE TITLE
Please support the lyrics of Spotify Japan.

### ISSUE THREAD

**Issue by fojno** [akashrchandran/syrics-web#16]
My spotify account is a Japan region account, and its lyrics provider is not Musixmatch, but Petitlyrics.
There are quite a few songs that have lyrics in the Japan region, but syrics shows no lyrics.
For example:
![Screenshot_20231201_170135](https://github.com/akashrchandran/syrics-web/assets/64184590/0e505bff-4fd3-4fe9-8934-72a30d773bef)
![2023-12-01_170913](https://github.com/akashrchandran/syrics-web/assets/64184590/e98dab1a-a41d-4f6a-b67f-057e59101dc8)

If possible, can you support the lyrics download for Spotify Japan?

**Comment by akashrchandran** [comment]
The issue is that the current Syrics web version relies on a free Spotify account, preventing the download of many songs with lyrics. I had a premium account supporting it for a while, but now I can't afford it. If you've got a premium account, you can use this tool to grab the lyrics you want: https://github.com/akashrchandran/syrics.


If others want to contribute, they can either donate a premium account or contribute funds. I'll use the money to buy a premium account and integrate it into the web service. You can download directly using the open-source tool without the need for any donations as well.
