### ISSUE TITLE
No Lyrics Found ):

### ISSUE THREAD

**Issue by de1ia** [akashrchandran/syrics-web#20]
There are lyrics on spotify but when I paste the link in syrics it doesn't work, please fix )':

**Comment by akashrchandran** [comment]
Please share the links of the song, that you have had this problem with. Thank you.

**Comment by de1ia** [comment]
https://open.spotify.com/track/1MgKrTpsZgUBT5bhjCPPic?si=UsleoiO0QXGoR8V2z9ZGEQ 

please help me!

**Comment by de1ia** [comment]
still not working 😭

**Comment by akashrchandran** [comment]
Sorry for the late reply, but the issue is not with the program; it's with Spotify. The lyrics are region-locked, mainly due to licensing issues.

You may be able to download the lyrics with your own account. Try out the command-line version of [Syrics](https://github.com/akashrchandran/syrics), where you can log in with your own account.

**Comment by de1ia** [comment]
how to use that

**Comment by akashrchandran** [comment]
> how to use that

Refer to the README file for clear instructions.

**Comment by de1ia** [comment]
> > how to use that
> 
> Refer to the README file for clear instructions.
make a video on how to use it, thanks

**Comment by de1ia** [comment]
make a video on how to use it, thanks

**Comment by akashrchandran** [comment]
Try to learn python by watching the videos on YouTube. I don't have time to create video tutorials.
